# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://cvlab-unibo.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Learning Depth Estimation for Transparent and Mirror Surfaces
# Description of the Site
description: Accepted at ICCV2023.
# URL of Image of the Site
site-image:
# Keywords of the Site
site-keywords: Deep Learning, Depth, Disparity, Segmentation, Monocular, Mono, Stereo, Transparent, Glass, Specular, Reflective, non-Lambertian
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section
heroimage:

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email:
facebook_username:
twitter_username:
instagram_username:
linkedin_username:
github_username:  arcanoXIII/learning_depth_estimation_for_transparent_and_mirror_surfaces
youtube_channel_id: 
reddit_username:
behance_username:
dribbble_username:
spotify_username:
site_name: "https://www.vision.deis.unibo.it/"

# Google Analytics
google-analytics:

# Disqus
disqus-shortname: Depth4ToM

# Name of the Author
author-name: Alex Costanzino
# URL for the Image of the Author
author-image:
# 60 Words About the Author
author-about: 
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
